# Generated by Django 5.1 on 2025-04-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=70)),
                ('c_descr', models.TextField(max_length=70)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='driver_registeration',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_full_name', models.TextField(max_length=70)),
                ('d_email', models.EmailField(max_length=80)),
                ('d_passwd', models.CharField(max_length=35)),
                ('d_otp', models.IntegerField()),
                ('d_otp_used', models.BooleanField()),
                ('d_created_at', models.DateTimeField()),
                ('d_login_at', models.DateTimeField(blank=True, null=True)),
                ('d_login_status', models.IntegerField()),
                ('d_birth_date', models.DateField(null=True)),
                ('d_activity_status', models.IntegerField()),
                ('driver_details_status', models.IntegerField()),
                ('driver_bnk_status', models.IntegerField()),
                ('d_address_pin', models.IntegerField()),
                ('driver_approval_status', models.IntegerField()),
            ],
            options={
                'verbose_name': 'driver_registeration',
                'verbose_name_plural': 'driver_registeration',
                'db_table': 'driver_registeration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='user_registeration',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_full_name', models.TextField(max_length=70)),
                ('u_email', models.EmailField(max_length=80)),
                ('u_passwd', models.CharField(max_length=35)),
                ('u_otp', models.IntegerField()),
                ('u_otp_used', models.BooleanField()),
                ('u_created_at', models.DateTimeField()),
                ('u_login_at', models.DateTimeField(blank=True, null=True)),
                ('u_login_status', models.IntegerField()),
                ('u_birth_date', models.DateField(null=True)),
                ('u_is_admin', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user_registeration',
                'verbose_name_plural': 'user_registeration',
                'db_table': 'user_registeration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='category_count',
            fields=[
                ('cat_count_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_count', models.IntegerField()),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.category')),
            ],
            options={
                'verbose_name': 'category_count',
                'verbose_name_plural': 'category_count',
                'db_table': 'category_count',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='driver_account_details',
            fields=[
                ('d_acc_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_accnt_no', models.IntegerField()),
                ('d_acc_ifs', models.TextField(max_length=90)),
                ('d_branch_name', models.TextField(max_length=100)),
                ('d_bank_name', models.TextField(max_length=100)),
                ('d_bank_accept', models.IntegerField()),
                ('d_image_doc', models.ImageField(upload_to='bankpassbook/')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.driver_registeration')),
            ],
            options={
                'verbose_name': 'driver_account_details',
                'verbose_name_plural': 'driver_account_details',
                'db_table': 'driver_account_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='package_count',
            fields=[
                ('pack_count_id', models.AutoField(primary_key=True, serialize=False)),
                ('pack_count', models.IntegerField()),
                ('pack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.category')),
            ],
            options={
                'verbose_name': 'package_count',
                'verbose_name_plural': 'package_count',
                'db_table': 'package_count',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='packages',
            fields=[
                ('pack_id', models.AutoField(primary_key=True, serialize=False)),
                ('pack_name', models.TextField(max_length=70)),
                ('pack_price', models.IntegerField()),
                ('pack_descr', models.TextField(max_length=70)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.category')),
            ],
            options={
                'verbose_name': 'packages',
                'verbose_name_plural': 'packages',
                'db_table': 'packages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='vehicle_choice',
            fields=[
                ('vehicle_ch_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_ch_name', models.TextField(max_length=70)),
                ('vehicle_ch_height', models.IntegerField()),
                ('vehicle_ch_width', models.IntegerField()),
                ('vehicle_ch_length', models.IntegerField()),
                ('vehicle_ch_km_price', models.IntegerField()),
                ('vehicle_ch_capacity', models.IntegerField()),
                ('vehicle_image', models.ImageField(upload_to='adminviehcle/')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.packages')),
            ],
            options={
                'verbose_name': 'vehicle_choice',
                'verbose_name_plural': 'vehicle_choice',
                'db_table': 'vehicle_choice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='driver_details',
            fields=[
                ('d_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_vehicle_no', models.TextField(max_length=40)),
                ('d_licence', models.ImageField(upload_to='driverlicence/')),
                ('d_vehicle_r_c', models.ImageField(upload_to='driverrc/')),
                ('d_vehicle_accept', models.IntegerField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.driver_registeration')),
                ('driver_vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.vehicle_choice')),
            ],
            options={
                'verbose_name': 'driver_details',
                'verbose_name_plural': 'driver_details',
                'db_table': 'driver_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='booking_details',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_address', models.TextField()),
                ('from_pincode', models.IntegerField()),
                ('from_contact', models.IntegerField()),
                ('to_address', models.TextField()),
                ('to_pincode', models.IntegerField()),
                ('to_contact', models.IntegerField()),
                ('driver_all_STATUS', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('total_pay_amount', models.IntegerField()),
                ('driver_amount', models.IntegerField()),
                ('portal_profit_amount', models.IntegerField()),
                ('total_no_km_travel', models.IntegerField()),
                ('booking_date', models.DateTimeField()),
                ('booking_status', models.IntegerField()),
                ('completion_otp', models.IntegerField(null=True)),
                ('driver_all_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.driver_registeration')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.packages')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.user_registeration')),
                ('vehicle_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.vehicle_choice')),
            ],
            options={
                'verbose_name': 'booking_details',
                'verbose_name_plural': 'booking_details',
                'db_table': 'booking_details',
                'managed': True,
            },
        ),
    ]
