# Generated by Django 5.1 on 2025-04-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packersmoversadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='driverLocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packersmoversadmin.driver_registeration')),
            ],
        ),
    ]
